/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-14 07:20:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


if(session.getAttribute("user") == null) {
    response.sendRedirect("index.jsp");
}
String userEmail = (String)session.getAttribute("user");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Pharmacy Management Dashboard</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <!-- Lucide Icons -->\r\n");
      out.write("    <script src=\"https://unpkg.com/lucide@latest\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"dashboard-layout\">\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <div class=\"nav-brand\">\r\n");
      out.write("                <i data-lucide=\"pill\" class=\"primary\"></i>\r\n");
      out.write("                PharmaCare MS\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"nav-actions\">\r\n");
      out.write("                <div class=\"user-badge\">\r\n");
      out.write("                    <i data-lucide=\"user\" style=\"width:16px\"></i>\r\n");
      out.write("                    ");
      out.print( userEmail );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"logout.jsp\" class=\"btn-logout\">\r\n");
      out.write("                    <i data-lucide=\"log-out\" style=\"width:16px; display:inline; vertical-align:middle\"></i>\r\n");
      out.write("                    Logout\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        \r\n");
      out.write("        <main class=\"main-content\">\r\n");
      out.write("            <div class=\"welcome-banner animate-fade-in\">\r\n");
      out.write("                <h2>Welcome back, PharmaCare Pro!</h2>\r\n");
      out.write("                <p>Manage your inventory, track sales, and streamline your pharmacy operations all from one central dashboard.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"stats-grid\">\r\n");
      out.write("                <a href=\"medicines.jsp\" class=\"stat-card animate-fade-in\" style=\"animation-delay: 0.1s\">\r\n");
      out.write("                    <div class=\"card-icon-wrapper\">\r\n");
      out.write("                        <i data-lucide=\"pill\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3>Medicines</h3>\r\n");
      out.write("                    <p>Add, edit and manage your medical inventory and drug details.</p>\r\n");
      out.write("                </a>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"stock.jsp\" class=\"stat-card animate-fade-in\" style=\"animation-delay: 0.2s\">\r\n");
      out.write("                    <div class=\"card-icon-wrapper\" style=\"background: rgba(59, 130, 246, 0.1); color: var(--accent);\">\r\n");
      out.write("                        <i data-lucide=\"package\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3>Stock Management</h3>\r\n");
      out.write("                    <p>Monitor stock levels, set alerts for low inventory and manage supplies.</p>\r\n");
      out.write("                </a>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"billing.jsp\" class=\"stat-card animate-fade-in\" style=\"animation-delay: 0.3s\">\r\n");
      out.write("                    <div class=\"card-icon-wrapper\" style=\"background: rgba(245, 158, 11, 0.1); color: #f59e0b;\">\r\n");
      out.write("                        <i data-lucide=\"credit-card\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3>Billing & POS</h3>\r\n");
      out.write("                    <p>Create professional invoices and manage customer transactions smoothly.</p>\r\n");
      out.write("                </a>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"reports.jsp\" class=\"stat-card animate-fade-in\" style=\"animation-delay: 0.4s\">\r\n");
      out.write("                    <div class=\"card-icon-wrapper\" style=\"background: rgba(139, 92, 246, 0.1); color: #8b5cf6;\">\r\n");
      out.write("                        <i data-lucide=\"bar-chart-3\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3>Sales Reports</h3>\r\n");
      out.write("                    <p>View detailed analytics and performance reports of your pharmacy sales.</p>\r\n");
      out.write("                </a>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"staff.jsp\" class=\"stat-card animate-fade-in\" style=\"animation-delay: 0.5s\">\r\n");
      out.write("                    <div class=\"card-icon-wrapper\" style=\"background: rgba(236, 72, 153, 0.1); color: #ec4899;\">\r\n");
      out.write("                        <i data-lucide=\"users\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3>Staff Management</h3>\r\n");
      out.write("                    <p>Manage employee access, roles and pharmacy staff permissions.</p>\r\n");
      out.write("                </a>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"settings.jsp\" class=\"stat-card animate-fade-in\" style=\"animation-delay: 0.6s\">\r\n");
      out.write("                    <div class=\"card-icon-wrapper\" style=\"background: rgba(100, 116, 139, 0.1); color: #64748b;\">\r\n");
      out.write("                        <i data-lucide=\"settings\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3>System Settings</h3>\r\n");
      out.write("                    <p>Configure app preferences, backup data and update your profile.</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        lucide.createIcons();\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
