/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-14 07:20:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class medicines_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


if(session.getAttribute("user") == null) {
    response.sendRedirect("index.jsp");
}
String userEmail = (String)session.getAttribute("user");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Medicines Inventory - PharmaCare</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("    <script src=\"https://unpkg.com/lucide@latest\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"dashboard-layout\">\n");
      out.write("        <nav class=\"navbar\">\n");
      out.write("            <div class=\"nav-brand\">\n");
      out.write("                <a href=\"dashboard.jsp\" style=\"text-decoration: none; color: inherit; display: flex; align-items: center; gap: 10px;\">\n");
      out.write("                    <i data-lucide=\"pill\" class=\"primary\"></i>\n");
      out.write("                    PharmaCare MS\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"nav-actions\">\n");
      out.write("                <div class=\"user-badge\">\n");
      out.write("                    <i data-lucide=\"user\" style=\"width:16px\"></i>\n");
      out.write("                    ");
      out.print( userEmail );
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <a href=\"logout.jsp\" class=\"btn-logout\">Logout</a>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        \n");
      out.write("        <main class=\"main-content\">\n");
      out.write("            <div class=\"page-header animate-fade-in\">\n");
      out.write("                <div class=\"page-title\">\n");
      out.write("                    <h2>Medicines Inventory</h2>\n");
      out.write("                    <p>Manage and track your pharmaceutical products.</p>\n");
      out.write("                </div>\n");
      out.write("                <button class=\"btn btn-primary btn-sm\">\n");
      out.write("                    <i data-lucide=\"plus\" style=\"width:16px\"></i>\n");
      out.write("                    Add New Medicine\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"table-actions animate-fade-in\" style=\"margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center;\">\n");
      out.write("                <div class=\"search-wrapper\">\n");
      out.write("                    <i data-lucide=\"search\" class=\"search-icon\"></i>\n");
      out.write("                    <input type=\"text\" class=\"search-input\" placeholder=\"Search medicines by name or ID...\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"filter-group\" style=\"display: flex; gap: 10px;\">\n");
      out.write("                    <select class=\"form-input\" style=\"width: 150px; padding: 8px;\">\n");
      out.write("                        <option>All Categories</option>\n");
      out.write("                        <option>Tablets</option>\n");
      out.write("                        <option>Syrups</option>\n");
      out.write("                        <option>Injections</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"table-container animate-fade-in\">\n");
      out.write("                <table>\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>ID</th>\n");
      out.write("                            <th>Medicine Name</th>\n");
      out.write("                            <th>Category</th>\n");
      out.write("                            <th>Manufacturer</th>\n");
      out.write("                            <th>Price</th>\n");
      out.write("                            <th>Status</th>\n");
      out.write("                            <th>Actions</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>#MED-001</td>\n");
      out.write("                            <td style=\"font-weight: 500;\">Paracetamol 500mg</td>\n");
      out.write("                            <td>Tablet</td>\n");
      out.write("                            <td>Generic Pharma</td>\n");
      out.write("                            <td>$5.00</td>\n");
      out.write("                            <td><span class=\"badge badge-success\">In Stock</span></td>\n");
      out.write("                            <td>\n");
      out.write("                                <button class=\"btn-logout\" style=\"background: var(--bg-main); color: var(--accent); padding: 5px 10px;\">Edit</button>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>#MED-002</td>\n");
      out.write("                            <td style=\"font-weight: 500;\">Amoxicillin 250mg</td>\n");
      out.write("                            <td>Capsule</td>\n");
      out.write("                            <td>BioLabs Inc.</td>\n");
      out.write("                            <td>$12.50</td>\n");
      out.write("                            <td><span class=\"badge badge-success\">In Stock</span></td>\n");
      out.write("                            <td>\n");
      out.write("                                <button class=\"btn-logout\" style=\"background: var(--bg-main); color: var(--accent); padding: 5px 10px;\">Edit</button>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>#MED-003</td>\n");
      out.write("                            <td style=\"font-weight: 500;\">Cough Relief Syrup</td>\n");
      out.write("                            <td>Syrup</td>\n");
      out.write("                            <td>NatureCure</td>\n");
      out.write("                            <td>$8.75</td>\n");
      out.write("                            <td><span class=\"badge badge-warning\">Low Stock</span></td>\n");
      out.write("                            <td>\n");
      out.write("                                <button class=\"btn-logout\" style=\"background: var(--bg-main); color: var(--accent); padding: 5px 10px;\">Edit</button>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>#MED-004</td>\n");
      out.write("                            <td style=\"font-weight: 500;\">Vitamin C Tablets</td>\n");
      out.write("                            <td>Supplement</td>\n");
      out.write("                            <td>VitaPlus</td>\n");
      out.write("                            <td>$15.00</td>\n");
      out.write("                            <td><span class=\"badge badge-danger\">Out of Stock</span></td>\n");
      out.write("                            <td>\n");
      out.write("                                <button class=\"btn-logout\" style=\"background: var(--bg-main); color: var(--accent); padding: 5px 10px;\">Edit</button>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </main>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        lucide.createIcons();\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
