/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-14 07:20:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reports_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


if(session.getAttribute("user") == null) {
    response.sendRedirect("index.jsp");
}
String userEmail = (String)session.getAttribute("user");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Sales Reports - PharmaCare</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("    <script src=\"https://unpkg.com/lucide@latest\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"dashboard-layout\">\n");
      out.write("        <nav class=\"navbar\">\n");
      out.write("            <div class=\"nav-brand\">\n");
      out.write("                <a href=\"dashboard.jsp\" style=\"text-decoration: none; color: inherit; display: flex; align-items: center; gap: 10px;\">\n");
      out.write("                    <i data-lucide=\"bar-chart-3\" class=\"primary\"></i>\n");
      out.write("                    PharmaCare MS\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"nav-actions\">\n");
      out.write("                <div class=\"user-badge\">\n");
      out.write("                    <i data-lucide=\"user\" style=\"width:16px\"></i>\n");
      out.write("                    ");
      out.print( userEmail );
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <a href=\"logout.jsp\" class=\"btn-logout\">Logout</a>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        \n");
      out.write("        <main class=\"main-content\">\n");
      out.write("            <div class=\"page-header animate-fade-in\">\n");
      out.write("                <div class=\"page-title\">\n");
      out.write("                    <h2>Sales & Analytics</h2>\n");
      out.write("                    <p>Track your business performance and top selling items.</p>\n");
      out.write("                </div>\n");
      out.write("                <div style=\"display: flex; gap: 10px;\">\n");
      out.write("                    <button class=\"btn btn-outline btn-sm\" style=\"border: 1px solid var(--border); background: white;\">\n");
      out.write("                        Month Selection\n");
      out.write("                        <i data-lucide=\"chevron-down\" style=\"width:14px; margin-left: 5px;\"></i>\n");
      out.write("                    </button>\n");
      out.write("                    <button class=\"btn btn-primary btn-sm\">\n");
      out.write("                        <i data-lucide=\"file-text\" style=\"width:16px\"></i>\n");
      out.write("                        Download PDF\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"analytics-grid animate-fade-in\">\n");
      out.write("                <div class=\"analytic-card\">\n");
      out.write("                    <div class=\"card-icon-wrapper\" style=\"background: rgba(16, 185, 129, 0.1); color: var(--primary);\">\n");
      out.write("                        <i data-lucide=\"dollar-sign\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"analytic-value\">$12,450.00</div>\n");
      out.write("                        <div class=\"analytic-label\">Total Revenue (Monthly)</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"analytic-card\">\n");
      out.write("                    <div class=\"card-icon-wrapper\" style=\"background: rgba(59, 130, 246, 0.1); color: var(--accent);\">\n");
      out.write("                        <i data-lucide=\"shopping-bag\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"analytic-value\">842</div>\n");
      out.write("                        <div class=\"analytic-label\">Total Transactions</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"analytic-card\">\n");
      out.write("                    <div class=\"card-icon-wrapper\" style=\"background: rgba(139, 92, 246, 0.1); color: #8b5cf6;\">\n");
      out.write("                        <i data-lucide=\"trending-up\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"analytic-value\">+15.4%</div>\n");
      out.write("                        <div class=\"analytic-label\">Growth vs Last Month</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div style=\"display: grid; grid-template-columns: 2fr 1fr; gap: 30px;\" class=\"animate-fade-in\">\n");
      out.write("                <!-- Sales Chart Placeholder -->\n");
      out.write("                <div class=\"table-container\" style=\"padding: 24px;\">\n");
      out.write("                    <h3 style=\"margin-bottom: 20px;\">Revenue Trend</h3>\n");
      out.write("                    <div class=\"placeholder-chart\">\n");
      out.write("                        <div class=\"chart-bar\" style=\"height: 40%;\"></div>\n");
      out.write("                        <div class=\"chart-bar\" style=\"height: 60%;\"></div>\n");
      out.write("                        <div class=\"chart-bar\" style=\"height: 55%;\"></div>\n");
      out.write("                        <div class=\"chart-bar\" style=\"height: 85%;\"></div>\n");
      out.write("                        <div class=\"chart-bar\" style=\"height: 70%;\"></div>\n");
      out.write("                        <div class=\"chart-bar\" style=\"height: 90%;\"></div>\n");
      out.write("                        <div class=\"chart-bar\" style=\"height: 100%;\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div style=\"display: flex; justify-content: space-between; margin-top: 10px; color: var(--text-muted); font-size: 12px;\">\n");
      out.write("                        <span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Top Products -->\n");
      out.write("                <div class=\"table-container\" style=\"padding: 24px;\">\n");
      out.write("                    <h3 style=\"margin-bottom: 20px;\">Top Selling</h3>\n");
      out.write("                    <div style=\"display: flex; flex-direction: column; gap: 15px;\">\n");
      out.write("                        <div style=\"display: flex; justify-content: space-between; align-items: center;\">\n");
      out.write("                            <div style=\"display: flex; align-items: center; gap: 10px;\">\n");
      out.write("                                <div style=\"width: 8px; height: 8px; background: var(--primary); border-radius: 50%;\"></div>\n");
      out.write("                                <span style=\"font-size: 14px; font-weight: 500;\">Paracetamol</span>\n");
      out.write("                            </div>\n");
      out.write("                            <span style=\"font-size: 13px; color: var(--text-muted);\">452 sold</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div style=\"display: flex; justify-content: space-between; align-items: center;\">\n");
      out.write("                            <div style=\"display: flex; align-items: center; gap: 10px;\">\n");
      out.write("                                <div style=\"width: 8px; height: 8px; background: var(--accent); border-radius: 50%;\"></div>\n");
      out.write("                                <span style=\"font-size: 14px; font-weight: 500;\">Vitamin C</span>\n");
      out.write("                            </div>\n");
      out.write("                            <span style=\"font-size: 13px; color: var(--text-muted);\">312 sold</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div style=\"display: flex; justify-content: space-between; align-items: center;\">\n");
      out.write("                            <div style=\"display: flex; align-items: center; gap: 10px;\">\n");
      out.write("                                <div style=\"width: 8px; height: 8px; background: #8b5cf6; border-radius: 50%;\"></div>\n");
      out.write("                                <span style=\"font-size: 14px; font-weight: 500;\">Cough Syrup</span>\n");
      out.write("                            </div>\n");
      out.write("                            <span style=\"font-size: 13px; color: var(--text-muted);\">198 sold</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </main>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        lucide.createIcons();\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
